# =============================
#下载好文件名改为mpv.conf在导入！
#7.25日更新，开启缓存，优化网盘播放！
#电视请勿使用此配置文件
# 高画质 · 低延迟 · 低功耗
# ============================================================

    
# --- Vulkan 渲染架构（低延迟 & 高画质） ---
vulkan-swap-mode=mailbox
swapchain-depth=3
vulkan-queue-count=2
vulkan-async-compute=yes
vulkan-async-transfer=yes
video-latency-hacks=yes
gpu-dumb-mode=no

# --- 核心画质设置（10bit / HDR / 抖动） ---
dither-depth=10
dither=fruit
temporal-dither=yes
fbo-format=rgba16f
video-output-levels=full
interpolation=no
tone-mapping=auto
gamut-mapping-mode=auto

#关闭AV1胶卷颗粒以提升清晰度，开启HDR10+元数据透传
vf=format:film-grain=no:hdr10plus=yes

# --- 解码器设置
hwdec=mediacodec
vo=gpu-next
gpu-api=vulkan
gpu-context=androidvk
video-sync=display-resample

# --- 网盘网络优化（防限速/防断连） ---
network-timeout=60
stream-lavf-o=reconnect=1
stream-lavf-o=reconnect_at_eof=1
stream-lavf-o=reconnect_streamed=1
stream-lavf-o=reconnect_delay_max=4
stream-lavf-o=buffer_size=1310720
stream-lavf-o=rw_timeout=40000000
user-agent=Mozilla/5.0 (Android; Mobile) Chrome/120.0 Mobile Safari/537.36
demuxer-lavf-o=follow_redirects=1


#字幕音频相关
#让 MPV 播放视频时，优先加载中文音轨和中文字幕。
alang=zh,chi,chs,sc,zh-hans,en,eng
slang=zh,chi,chs,sc,zh-hans,en,eng
#字幕混合，字幕不会出现在黑边空白处！
blend-subtitles=yes
# 启动默认音量
volume=30
# 程序最大音量
volume-max=200

# 安卓低延迟高质量音频输出
ao=aaudio
# 立体声适配手机平板喇叭/耳机
audio-channels=stereo
# 多声道自动均衡下混
audio-normalize-downmix=yes
# 音频缓冲平衡延迟与卡顿
audio-buffer=0.5
audio-stream-silence=yes
# 高精度16bit音频处理，细节更多
audio-format=s16
#强制音频采样率输出为96kHz，比默认48kHz采样精度更高，高频细节、配乐泛音更丰富，提升细腻听感。
audio-samplerate=96000
# 多声道音轨自动下混立体声
ad-lavc-downmix=yes
# AC3/EAC3杜比音频动态压缩完全关闭
ad-lavc-ac3drc=0

#性能预设配置，稳定，流畅，省电。
profile=fast


# --- HDR 直通 ---
# 直通核心：把原始色彩/伽马标记传给屏幕
[HDR]
profile-cond=get("video-params/primaries") == "bt.2020" and get("video-params/gamma") == "pq"
target-trc=pq
target-prim=bt.2020
target-colorspace-hint=yes
target-colorspace-hint-mode=source
hdr-compute-peak=no

[cache]
# 配置触发条件：仅网络流媒体启用该缓存配置
profile-cond=demuxer_via_network
# 开启缓存功能
cache=yes
# 播放器暂停时继续预加载缓存
cache-pause=yes
# 预缓存时长：300秒视频数据
cache-secs=300
# 最大向前缓存容量1024MB
demuxer-max-bytes=1024MiB
# 向后留存缓存上限1024MB
demuxer-max-back-bytes=1024MiB
# lavf底层参数：断网自动重连，已加载的流媒体也尝试重连，最长重连等待5秒
stream-lavf-o=reconnect=1,reconnect_streamed=1,reconnect_delay_max=5